# Generated by Django 4.2.9 on 2026-04-24 03:15

import apps.appointments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.appointments.models.appointment_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appointments.appointment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
