import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const translations = {
  uz: {
    // ─── Nav ───────────────────────────────────────────────────────────────────
    dashboard: "Bosh sahifa",
    appointments: "Qabullar",
    bookAppointment: "Qabul Belgilash",
    patients: "Bemorlar",
    doctors: "Doktorlar",
    departments: "Bo'limlar",
    users: "Foydalanuvchilar",
    billing: "To'lovlar",
    blog: "Blog",
    profile: "Profil",
    schedule: "Jadval",
    medicalRecords: "Tibbiy Yozuvlar",

    // ─── Auth ──────────────────────────────────────────────────────────────────
    login: "Kirish",
    logout: "Chiqish",
    register: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",

    // ─── Common ────────────────────────────────────────────────────────────────
    save: "Saqlash",
    saving: "Saqlanmoqda...",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    create: "Yaratish",
    search: "Qidirish",
    loading: "Yuklanmoqda...",
    close: "Yopish",
    add: "Qo'shish",
    update: "Yangilash",
    view: "Ko'rish",
    actions: "Amallar",
    back: "Orqaga",
    next: "Keyingi",
    continue: "Davom etish",
    confirm: "Tasdiqlash",
    yes: "Ha",
    no: "Yo'q",
    optional: "ixtiyoriy",
    required: "majburiy",
    all: "Barchasi",
    noData: "Ma'lumot yo'q",
    searchPlaceholder: "Qidirish...",
    noRecordsFound: "Yozuvlar topilmadi",
    allData: "Barcha ma'lumotlar",
    from: "dan",
    to: "gacha",
    at: "soat",
    or: "yoki",

    // ─── Roles ─────────────────────────────────────────────────────────────────
    admin: "Admin",
    doctor: "Doktor",
    nurse: "Hamshira",
    receptionist: "Registrator",
    patient: "Bemor",

    // ─── Statuses ──────────────────────────────────────────────────────────────
    pending: "Kutilmoqda",
    approved: "Tasdiqlangan",
    completed: "Bajarilgan",
    cancelled: "Bekor qilingan",
    noShow: "Kelmadi",
    paid: "To'langan",
    unpaid: "To'lanmagan",
    partiallyPaid: "Qisman to'langan",
    allStatuses: "Barcha holatlar",

    // ─── Table headers ──────────────────────────────────────────────────────────
    name: "Ism",
    firstName: "Ism",
    lastName: "Familiya",
    fullName: "To'liq ism",
    phone: "Telefon",
    role: "Rol",
    gender: "Jins",
    male: "Erkak",
    female: "Ayol",
    username: "Foydalanuvchi nomi",
    verified: "Tasdiqlangan",
    active: "Faol",
    date: "Sana",
    time: "Vaqt",
    status: "Holat",
    reason: "Sabab",
    amount: "Miqdor",
    dateTime: "Sana & Vaqt",
    createdAt: "Qo'shilgan",

    // ─── Dashboard ─────────────────────────────────────────────────────────────
    adminDashboard: "Admin Paneli",
    hospitalOverview: "Shifoxona umumiy ko'rinishi va ko'rsatkichlari",
    totalPatients: "Jami Bemorlar",
    activeDoctors: "Faol Doktorlar",
    todayAppointments: "Bugungi Qabullar",
    monthlyRevenue: "Oylik Daromad",
    totalRevenue: "Jami Daromad",
    pendingAppointments: "Kutilayotgan Qabullar",
    unpaidBills: "To'lanmagan Hisob-kitoblar",
    appointmentsByStatus: "Qabullar holati bo'yicha",
    recentAppointments: "So'nggi Qabullar",
    doctorDashboard: "Doktor Paneli",
    todaySchedule: "Bugungi Jadval",
    noAppointmentsToday: "Bugun qabullar yo'q",
    pendingApproval: "Tasdiq kutmoqda",
    completedToday: "Bugun bajarilgan",
    myHealthDashboard: "Mening Sog'liq Paneliim",
    upcomingAppointments: "Kelgusi Qabullar",
    noUpcomingAppointments: "Kelgusi qabullar yo'q",
    nextAppointment: "Keyingi Qabul",
    totalAppointmentsCount: "Jami Qabullar",
    staffDashboard: "Xodim Paneli",
    goodMorning: "Xayrli tong",
    generalConsultation: "Umumiy maslahat",

    // ─── Appointments ──────────────────────────────────────────────────────────
    noAppointments: "Qabullar topilmadi",
    bookAppt: "Qabul Belgilash",
    approveAppt: "Tasdiqlash",
    rejectAppt: "Rad etish",
    completeAppt: "Bajarildi deb belgilash",
    cancelAppt: "Bekor qilish",
    deleteAppt: "O'chirish",
    cancelReason: "Bekor qilish sababi",
    rejectionReason: "Rad etish sababi",
    appointmentDetails: "Qabul Tafsilotlari",
    keepAppt: "Saqlash",
    confirmCancel: "Bekor qilishni tasdiqlaysizmi?",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    symptoms: "Belgilar",
    notes: "Izohlar",
    cancellationReason: "Bekor qilish sababi",
    uploadedImages: "Yuklangan rasmlar",
    insurance: "Sug'urta raqami",
    emergencyContact: "Favqulodda aloqa",
    emergencyPhone: "Favqulodda telefon",
    address: "Manzil",
    allergies: "Allergiyalar",
    chronicConditions: "Surunkali kasalliklar",
    bloodGroup: "Qon guruhi",
    age: "Yosh",
    cancelApptFor: "Qabulni bekor qilish",
    rejectApptFor: "Qabulni rad etish",
    searchPatientOrDoctor: "Bemor yoki doktor bo'yicha qidirish...",

    // ─── Patients ──────────────────────────────────────────────────────────────
    noPatients: "Bemorlar topilmadi",
    patientDetails: "Bemor Tafsilotlari",
    patientHealthHistory: "Bemor sog'liq tarixi",
    dateOfBirth: "Tug'ilgan sana",
    searchByNameOrEmail: "Ism yoki email bo'yicha qidirish...",
    patientsRegistered: "ro'yxatga olingan bemorlar",
    registeredPatients: "Ro'yxatga olingan bemorlar",

    // ─── Doctors ───────────────────────────────────────────────────────────────
    doctorsList: "Doktorlar",
    doctorsListFull: "Barcha doktorlar ro'yxati va ma'lumotlari",
    doctorInfo: "Doktor Ma'lumotlari",
    specialization: "Mutaxassislik",
    experience: "Tajriba",
    yearsExperience: "yil tajriba",
    consultation: "Konsultatsiya",
    available: "Mavjud",
    notAvailable: "Band",
    bio: "Haqida",
    department: "Bo'lim",
    licenseNumber: "Litsenziya raqami",
    qualification: "Malaka",
    workingSchedule: "Ish vaqti",
    workingHours: "Ish soatlari",
    weeklySchedule: "Haftalik jadval",
    noDoctors: "Doktorlar topilmadi",
    searchBySpecialization: "Ism yoki mutaxassislik bo'yicha qidirish...",
    bookWithDoctor: "Bu doktorga yozilish",
    yearsExp: "yil tajriba",
    perConsultation: "konsultatsiya",

    // ─── Medical Records ───────────────────────────────────────────────────────
    noMedicalRecords: "Tibbiy yozuvlar topilmadi",
    medicalRecordsSubtitle: "Bemorlar sog'liq tarixi va tashxislar",
    diagnosis: "Tashxis",
    followUp: "Nazorat ko'rik",
    recordDetails: "Yozuv Tafsilotlari",
    prescription: "Retsept",
    treatment: "Davolash",
    searchByDiagnosis: "Tashxis yoki bemor bo'yicha qidirish...",

    // ─── Billing ───────────────────────────────────────────────────────────────
    billingSubtitle: "Hisob-kitob boshqaruvi va to'lovlar",
    myBillsSubtitle: "Mening hisob-kitoblarim va to'lov tarixi",
    invoiceDetails: "Hisob-kitob Tafsilotlari",
    invoiceNumber: "Hisob-kitob raqami",
    balanceDue: "Qoldiq",
    amountPaid: "To'langan",
    subtotal: "Oraliq jami",
    discount: "Chegirma",
    tax: "Soliq",
    total: "Jami",
    dueDate: "To'lov muddati",
    paymentMethod: "To'lov usuli",
    processPayment: "To'lovni qayta ishlash",
    processing: "Qayta ishlanmoqda...",
    uploadReceipt: "Chek yuklash",
    submitReceipt: "Chekni yuborish",
    payViaCard: "Karta orqali to'lash",
    paymentScreenshot: "To'lov skrinshoti",
    cardNumber: "Karta raqami",
    amountPaidLabel: "To'langan miqdor",
    cardLastFour: "Karta raqami (oxirgi 4 raqam, ixtiyoriy)",
    noteLabel: "Izoh (ixtiyoriy)",
    clickToSelect: "Faylni tanlash uchun bosing",
    cash: "Naqd",
    card: "Karta",
    insuranceMethod: "Sug'urta",
    bankTransfer: "Bank o'tkazmasi",
    online: "Online",
    paymentReceipts: "To'lov cheklari",
    pendingReceiptsAlert: "tasdiqlash kutilayotgan to'lov cheki",
    noBillsFound: "Hisob-kitoblar topilmadi",
    searchInvoice: "Hisob-kitob yoki bemor bo'yicha qidirish...",
    invoiceCol: "Hisob-kitob",
    patientCol: "Bemor",
    amountCol: "Miqdor",
    paidCol: "To'langan",
    balanceCol: "Qoldiq",
    statusCol: "Holat",
    receiptCol: "Chek",
    dateCol: "Sana",
    actionsCol: "Amallar",
    paymentAmount: "To'lov miqdori",
    transferInstruction: "Quyidagi miqdorni kartamizga o'tkazing, so'ng to'lov tasdig'ining skrinshotini yuklang.",
    description: "Tavsif",

    // ─── Departments ───────────────────────────────────────────────────────────
    departmentInfo: "Bo'lim Ma'lumotlari",
    addDepartment: "Bo'lim Qo'shish",
    editDepartment: "Bo'limni Tahrirlash",
    deleteDepartment: "Bo'limni O'chirish",
    noDepartments: "Bo'limlar topilmadi",
    location: "Joylashuv",
    contactNumber: "Telefon",
    departmentName: "Bo'lim nomi",
    departmentsCount: "bo'lim",
    doctorsInDept: "Doktorlar",
    noDocsInDept: "Bu bo'limda doktorlar yo'q",
    deleteConfirmDept: "ni o'chirishni tasdiqlaysizmi? Bu amalni bekor qilib bo'lmaydi.",

    // ─── Blog ──────────────────────────────────────────────────────────────────
    blogSubtitle: "Tibbiy maslahatlar va sog'liq haqida maqolalar",
    newPost: "Yangi Maqola",
    editPost: "Maqolani Tahrirlash",
    deletePost: "Maqolani O'chirish",
    like: "Yoqdi",
    dislike: "Yoqmadi",
    comment: "Izoh",
    comments: "izohlar",
    reply: "Javob",
    noPostsYet: "Hali maqolalar yo'q",
    firstToShare: "Tibbiy maslahat ulashing.",
    noPostsAvailable: "Hali maqolalar mavjud emas.",
    postTitle: "Maqola sarlavhasi...",
    postContent: "Maqola matnini yozing...",
    postImage: "Rasm (ixtiyoriy)",
    publish: "E'lon qilish",
    writeComment: "Izoh yozing...",
    writeReply: "Javob yozing...",
    blogTitleLabel: "Sarlavha",
    blogContentLabel: "Matn",
    blogImageLabel: "Rasm (ixtiyoriy)",

    // ─── Users ─────────────────────────────────────────────────────────────────
    userManagement: "Foydalanuvchilar Boshqaruvi",
    allStaff: "Barcha xodimlar va ularning rollarini boshqaring",
    newEmployee: "Yangi Xodim",
    createUser: "Foydalanuvchi Yaratish",
    editUser: "Foydalanuvchini Tahrirlash",
    deleteUser: "O'chirish",
    promoteToAdmin: "Admin qilish",
    activateUser: "Faollashtirish / O'chirish",
    verifyUser: "Tasdiqlash holati",
    autoGenPassword: "Avtomatik parol yaratish",
    loginPassword: "Login Paroli",
    givePasswordToDoctor: "Bu parolni doktorgа bering — tizimga kirish uchun ishlatadi.",
    accountCreated: "Hisob Yaratildi!",
    passwordForDoctor: "Quyidagi parolni doktorgа bering",
    copyPassword: "Nusxa olish",
    understood: "Tushunarli",
    savePassword: "Parolni xavfsiz joyga saqlang!",
    confirmDeleteUser: "ni o'chirishni tasdiqlaysizmi?",
    confirmPromoteAdmin: "ni admin qilib tayinlaysizmi?",
    profileImage: "Profil rasm",
    imageOptional: "Rasm yuklash ixtiyoriy",
    minPassword: "Minimum 8 ta belgi",
    repeatPassword: "Takrorlang",
    autoFromEmail: "Avtomatik email dan",
    doctorInfo2: "Doktor Ma'lumotlari",
    specialization2: "Mutaxassislik",
    departmentSelect: "Bo'lim (Department)",
    experienceYears: "Tajriba (yil)",
    consultationFee: "Konsultatsiya ($)",
    licenseField: "Litsenziya",
    bioField: "Ma'lumot / Bio",
    allRoles: "Barcha Rollar",

    // ─── Profile ───────────────────────────────────────────────────────────────
    myProfile: "Mening Profilim",
    personalInfo: "Shaxsiy Ma'lumotlar",
    changePassword: "Parolni O'zgartirish",
    doctorProfile: "Doktor Profili",
    patientProfile: "Bemor Profili",
    oldPassword: "Eski parol",
    newPassword: "Yangi parol",
    confirmPassword: "Parolni tasdiqlang",
    uploadAvatar: "Rasm Yuklash",
    avatarHint: "Profilingizga rasm qo'shing",
    saveChanges: "O'zgarishlarni Saqlash",
    passwordChanged: "Parol muvaffaqiyatli o'zgartirildi",
    profileUpdated: "Profil yangilandi",
  },

  ru: {
    // ─── Nav ───────────────────────────────────────────────────────────────────
    dashboard: "Главная",
    appointments: "Приёмы",
    bookAppointment: "Записаться",
    patients: "Пациенты",
    doctors: "Врачи",
    departments: "Отделения",
    users: "Пользователи",
    billing: "Оплата",
    blog: "Блог",
    profile: "Профиль",
    schedule: "Расписание",
    medicalRecords: "Мед. Записи",

    // ─── Auth ──────────────────────────────────────────────────────────────────
    login: "Войти",
    logout: "Выйти",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",

    // ─── Common ────────────────────────────────────────────────────────────────
    save: "Сохранить",
    saving: "Сохранение...",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Изменить",
    create: "Создать",
    search: "Поиск",
    loading: "Загрузка...",
    close: "Закрыть",
    add: "Добавить",
    update: "Обновить",
    view: "Просмотр",
    actions: "Действия",
    back: "Назад",
    next: "Далее",
    continue: "Продолжить",
    confirm: "Подтвердить",
    yes: "Да",
    no: "Нет",
    optional: "необязательно",
    required: "обязательно",
    all: "Все",
    noData: "Нет данных",
    searchPlaceholder: "Поиск...",
    noRecordsFound: "Записи не найдены",
    allData: "Все данные",
    from: "от",
    to: "до",
    at: "в",
    or: "или",

    // ─── Roles ─────────────────────────────────────────────────────────────────
    admin: "Админ",
    doctor: "Врач",
    nurse: "Медсестра",
    receptionist: "Регистратор",
    patient: "Пациент",

    // ─── Statuses ──────────────────────────────────────────────────────────────
    pending: "Ожидает",
    approved: "Подтверждён",
    completed: "Завершён",
    cancelled: "Отменён",
    noShow: "Не явился",
    paid: "Оплачено",
    unpaid: "Не оплачено",
    partiallyPaid: "Частично оплачено",
    allStatuses: "Все статусы",

    // ─── Table headers ──────────────────────────────────────────────────────────
    name: "Имя",
    firstName: "Имя",
    lastName: "Фамилия",
    fullName: "Полное имя",
    phone: "Телефон",
    role: "Роль",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    username: "Имя пользователя",
    verified: "Подтверждён",
    active: "Активен",
    date: "Дата",
    time: "Время",
    status: "Статус",
    reason: "Причина",
    amount: "Сумма",
    dateTime: "Дата & Время",
    createdAt: "Добавлен",

    // ─── Dashboard ─────────────────────────────────────────────────────────────
    adminDashboard: "Панель Администратора",
    hospitalOverview: "Обзор больницы и ключевые показатели",
    totalPatients: "Всего Пациентов",
    activeDoctors: "Активных Врачей",
    todayAppointments: "Приёмы Сегодня",
    monthlyRevenue: "Месячный Доход",
    totalRevenue: "Общий Доход",
    pendingAppointments: "Ожидающие Приёмы",
    unpaidBills: "Неоплаченные Счета",
    appointmentsByStatus: "Приёмы по Статусу",
    recentAppointments: "Недавние Приёмы",
    doctorDashboard: "Панель Врача",
    todaySchedule: "Расписание на сегодня",
    noAppointmentsToday: "Сегодня приёмов нет",
    pendingApproval: "Ожидают подтверждения",
    completedToday: "Завершено сегодня",
    myHealthDashboard: "Моя Медицинская Панель",
    upcomingAppointments: "Предстоящие Приёмы",
    noUpcomingAppointments: "Предстоящих приёмов нет",
    nextAppointment: "Следующий Приём",
    totalAppointmentsCount: "Всего Приёмов",
    staffDashboard: "Панель Сотрудника",
    goodMorning: "Доброе утро",
    generalConsultation: "Общая консультация",

    // ─── Appointments ──────────────────────────────────────────────────────────
    noAppointments: "Приёмы не найдены",
    bookAppt: "Записаться",
    approveAppt: "Подтвердить",
    rejectAppt: "Отклонить",
    completeAppt: "Завершить",
    cancelAppt: "Отменить",
    deleteAppt: "Удалить",
    cancelReason: "Причина отмены",
    rejectionReason: "Причина отклонения",
    appointmentDetails: "Детали Приёма",
    keepAppt: "Оставить",
    confirmCancel: "Отменить запись?",
    confirmDelete: "Удалить навсегда?",
    symptoms: "Симптомы",
    notes: "Заметки",
    cancellationReason: "Причина отмены",
    uploadedImages: "Загруженные фото",
    insurance: "№ страховки",
    emergencyContact: "Экстренный контакт",
    emergencyPhone: "Экстренный телефон",
    address: "Адрес",
    allergies: "Аллергии",
    chronicConditions: "Хронические болезни",
    bloodGroup: "Группа крови",
    age: "Возраст",
    cancelApptFor: "Отменить приём",
    rejectApptFor: "Отклонить приём",
    searchPatientOrDoctor: "Поиск по пациенту или врачу...",

    // ─── Patients ──────────────────────────────────────────────────────────────
    noPatients: "Пациенты не найдены",
    patientDetails: "Детали Пациента",
    patientHealthHistory: "История здоровья пациента",
    dateOfBirth: "Дата рождения",
    searchByNameOrEmail: "Поиск по имени или email...",
    patientsRegistered: "зарегистрированных пациентов",
    registeredPatients: "Зарегистрированные пациенты",

    // ─── Doctors ───────────────────────────────────────────────────────────────
    doctorsList: "Врачи",
    doctorsListFull: "Список всех врачей и информация",
    doctorInfo: "Информация о Враче",
    specialization: "Специализация",
    experience: "Опыт",
    yearsExperience: "лет опыта",
    consultation: "Консультация",
    available: "Доступен",
    notAvailable: "Занят",
    bio: "О враче",
    department: "Отделение",
    licenseNumber: "Номер лицензии",
    qualification: "Квалификация",
    workingSchedule: "Рабочее расписание",
    workingHours: "Рабочие часы",
    weeklySchedule: "Еженедельное расписание",
    noDoctors: "Врачи не найдены",
    searchBySpecialization: "Поиск по имени или специализации...",
    bookWithDoctor: "Записаться к этому врачу",
    yearsExp: "лет опыта",
    perConsultation: "консультация",

    // ─── Medical Records ───────────────────────────────────────────────────────
    noMedicalRecords: "Медицинские записи не найдены",
    medicalRecordsSubtitle: "История болезней и диагнозы пациентов",
    diagnosis: "Диагноз",
    followUp: "Повторный осмотр",
    recordDetails: "Детали Записи",
    prescription: "Рецепт",
    treatment: "Лечение",
    searchByDiagnosis: "Поиск по диагнозу или пациенту...",

    // ─── Billing ───────────────────────────────────────────────────────────────
    billingSubtitle: "Управление счетами и платежами",
    myBillsSubtitle: "Мои счета и история платежей",
    invoiceDetails: "Детали Счёта",
    invoiceNumber: "Номер счёта",
    balanceDue: "Остаток",
    amountPaid: "Оплачено",
    subtotal: "Подытог",
    discount: "Скидка",
    tax: "Налог",
    total: "Итого",
    dueDate: "Срок оплаты",
    paymentMethod: "Способ оплаты",
    processPayment: "Обработать платёж",
    processing: "Обработка...",
    uploadReceipt: "Загрузить чек",
    submitReceipt: "Отправить чек",
    payViaCard: "Оплата картой",
    paymentScreenshot: "Скриншот оплаты",
    cardNumber: "Номер карты",
    amountPaidLabel: "Оплаченная сумма",
    cardLastFour: "Номер карты (последние 4 цифры, необязательно)",
    noteLabel: "Примечание (необязательно)",
    clickToSelect: "Нажмите для выбора файла",
    cash: "Наличные",
    card: "Карта",
    insuranceMethod: "Страховка",
    bankTransfer: "Банковский перевод",
    online: "Онлайн",
    paymentReceipts: "Чеки оплаты",
    pendingReceiptsAlert: "чек(и) ожидают подтверждения",
    noBillsFound: "Счета не найдены",
    searchInvoice: "Поиск по счёту или пациенту...",
    invoiceCol: "Счёт",
    patientCol: "Пациент",
    amountCol: "Сумма",
    paidCol: "Оплачено",
    balanceCol: "Остаток",
    statusCol: "Статус",
    receiptCol: "Чек",
    dateCol: "Дата",
    actionsCol: "Действия",
    paymentAmount: "Сумма платежа",
    transferInstruction: "Переведите сумму на нашу карту, затем загрузите скриншот подтверждения оплаты.",
    description: "Описание",

    // ─── Departments ───────────────────────────────────────────────────────────
    departmentInfo: "Информация об Отделении",
    addDepartment: "Добавить Отделение",
    editDepartment: "Редактировать Отделение",
    deleteDepartment: "Удалить Отделение",
    noDepartments: "Отделения не найдены",
    location: "Местоположение",
    contactNumber: "Телефон",
    departmentName: "Название отделения",
    departmentsCount: "отделений",
    doctorsInDept: "Врачи",
    noDocsInDept: "В этом отделении нет врачей",
    deleteConfirmDept: "удалить? Это действие нельзя отменить.",

    // ─── Blog ──────────────────────────────────────────────────────────────────
    blogSubtitle: "Медицинские советы и статьи о здоровье",
    newPost: "Новая Статья",
    editPost: "Редактировать Статью",
    deletePost: "Удалить Статью",
    like: "Нравится",
    dislike: "Не нравится",
    comment: "Комментарий",
    comments: "комментариев",
    reply: "Ответить",
    noPostsYet: "Статей пока нет",
    firstToShare: "Поделитесь медицинским советом.",
    noPostsAvailable: "Статей пока нет.",
    postTitle: "Заголовок статьи...",
    postContent: "Напишите содержание статьи...",
    postImage: "Фото (необязательно)",
    publish: "Опубликовать",
    writeComment: "Написать комментарий...",
    writeReply: "Написать ответ...",
    blogTitleLabel: "Заголовок",
    blogContentLabel: "Содержание",
    blogImageLabel: "Фото (необязательно)",

    // ─── Users ─────────────────────────────────────────────────────────────────
    userManagement: "Управление Пользователями",
    allStaff: "Управление всеми сотрудниками и их ролями",
    newEmployee: "Новый Сотрудник",
    createUser: "Создать Пользователя",
    editUser: "Редактировать Пользователя",
    deleteUser: "Удалить",
    promoteToAdmin: "Назначить Админом",
    activateUser: "Активировать / Деактивировать",
    verifyUser: "Статус подтверждения",
    autoGenPassword: "Создать пароль автоматически",
    loginPassword: "Пароль для входа",
    givePasswordToDoctor: "Передайте этот пароль врачу — для входа в систему.",
    accountCreated: "Аккаунт создан!",
    passwordForDoctor: "Передайте врачу следующий пароль",
    copyPassword: "Скопировать",
    understood: "Понятно",
    savePassword: "Сохраните пароль в надёжном месте!",
    confirmDeleteUser: "удалить?",
    confirmPromoteAdmin: "назначить администратором?",
    profileImage: "Фото профиля",
    imageOptional: "Загрузка фото необязательна",
    minPassword: "Минимум 8 символов",
    repeatPassword: "Повторите",
    autoFromEmail: "Автоматически из email",
    doctorInfo2: "Данные Врача",
    specialization2: "Специализация",
    departmentSelect: "Отделение",
    experienceYears: "Опыт (лет)",
    consultationFee: "Консультация ($)",
    licenseField: "Лицензия",
    bioField: "Информация / Био",
    allRoles: "Все роли",

    // ─── Profile ───────────────────────────────────────────────────────────────
    myProfile: "Мой Профиль",
    personalInfo: "Личная Информация",
    changePassword: "Изменить Пароль",
    doctorProfile: "Профиль Врача",
    patientProfile: "Профиль Пациента",
    oldPassword: "Старый пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
    uploadAvatar: "Загрузить Фото",
    avatarHint: "Добавьте фото к вашему профилю",
    saveChanges: "Сохранить Изменения",
    passwordChanged: "Пароль успешно изменён",
    profileUpdated: "Профиль обновлён",
  },

  en: {
    // ─── Nav ───────────────────────────────────────────────────────────────────
    dashboard: "Dashboard",
    appointments: "Appointments",
    bookAppointment: "Book Appointment",
    patients: "Patients",
    doctors: "Doctors",
    departments: "Departments",
    users: "Users",
    billing: "Billing",
    blog: "Blog",
    profile: "Profile",
    schedule: "Schedule",
    medicalRecords: "Medical Records",

    // ─── Auth ──────────────────────────────────────────────────────────────────
    login: "Login",
    logout: "Logout",
    register: "Register",
    email: "Email",
    password: "Password",

    // ─── Common ────────────────────────────────────────────────────────────────
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    search: "Search",
    loading: "Loading...",
    close: "Close",
    add: "Add",
    update: "Update",
    view: "View",
    actions: "Actions",
    back: "Back",
    next: "Next",
    continue: "Continue",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    optional: "optional",
    required: "required",
    all: "All",
    noData: "No data",
    searchPlaceholder: "Search...",
    noRecordsFound: "No records found",
    allData: "All data",
    from: "from",
    to: "to",
    at: "at",
    or: "or",

    // ─── Roles ─────────────────────────────────────────────────────────────────
    admin: "Admin",
    doctor: "Doctor",
    nurse: "Nurse",
    receptionist: "Receptionist",
    patient: "Patient",

    // ─── Statuses ──────────────────────────────────────────────────────────────
    pending: "Pending",
    approved: "Approved",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No Show",
    paid: "Paid",
    unpaid: "Unpaid",
    partiallyPaid: "Partially Paid",
    allStatuses: "All Statuses",

    // ─── Table headers ──────────────────────────────────────────────────────────
    name: "Name",
    firstName: "First Name",
    lastName: "Last Name",
    fullName: "Full Name",
    phone: "Phone",
    role: "Role",
    gender: "Gender",
    male: "Male",
    female: "Female",
    username: "Username",
    verified: "Verified",
    active: "Active",
    date: "Date",
    time: "Time",
    status: "Status",
    reason: "Reason",
    amount: "Amount",
    dateTime: "Date & Time",
    createdAt: "Joined",

    // ─── Dashboard ─────────────────────────────────────────────────────────────
    adminDashboard: "Admin Dashboard",
    hospitalOverview: "Hospital overview and key metrics",
    totalPatients: "Total Patients",
    activeDoctors: "Active Doctors",
    todayAppointments: "Today's Appointments",
    monthlyRevenue: "Monthly Revenue",
    totalRevenue: "Total Revenue",
    pendingAppointments: "Pending Appointments",
    unpaidBills: "Unpaid Bills",
    appointmentsByStatus: "Appointments by Status",
    recentAppointments: "Recent Appointments",
    doctorDashboard: "Doctor Dashboard",
    todaySchedule: "Today's Schedule",
    noAppointmentsToday: "No appointments today",
    pendingApproval: "Pending Approval",
    completedToday: "Completed Today",
    myHealthDashboard: "My Health Dashboard",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",
    nextAppointment: "Next Appointment",
    totalAppointmentsCount: "Total Appointments",
    staffDashboard: "Staff Dashboard",
    goodMorning: "Good morning",
    generalConsultation: "General consultation",

    // ─── Appointments ──────────────────────────────────────────────────────────
    noAppointments: "No appointments found",
    bookAppt: "Book Appointment",
    approveAppt: "Approve",
    rejectAppt: "Reject",
    completeAppt: "Complete",
    cancelAppt: "Cancel",
    deleteAppt: "Delete",
    cancelReason: "Reason (optional)",
    rejectionReason: "Reason (optional)",
    appointmentDetails: "Appointment Details",
    keepAppt: "Keep",
    confirmCancel: "Cancel this appointment?",
    confirmDelete: "Delete permanently?",
    symptoms: "Symptoms",
    notes: "Notes",
    cancellationReason: "Cancellation Reason",
    uploadedImages: "Uploaded Images",
    insurance: "Insurance No",
    emergencyContact: "Emergency Contact",
    emergencyPhone: "Emergency Phone",
    address: "Address",
    allergies: "Allergies",
    chronicConditions: "Chronic Conditions",
    bloodGroup: "Blood Group",
    age: "Age",
    cancelApptFor: "Cancel Appointment",
    rejectApptFor: "Reject Appointment",
    searchPatientOrDoctor: "Search patient or doctor...",

    // ─── Patients ──────────────────────────────────────────────────────────────
    noPatients: "No patients found",
    patientDetails: "Patient Details",
    patientHealthHistory: "Patient health history and diagnoses",
    dateOfBirth: "Date of Birth",
    searchByNameOrEmail: "Search by name or email...",
    patientsRegistered: "registered patients",
    registeredPatients: "Registered Patients",

    // ─── Doctors ───────────────────────────────────────────────────────────────
    doctorsList: "Doctors",
    doctorsListFull: "All doctors list and information",
    doctorInfo: "Doctor Information",
    specialization: "Specialization",
    experience: "Experience",
    yearsExperience: "years experience",
    consultation: "Consultation",
    available: "Available",
    notAvailable: "Not Available",
    bio: "About",
    department: "Department",
    licenseNumber: "License Number",
    qualification: "Qualification",
    workingSchedule: "Working Schedule",
    workingHours: "Working Hours",
    weeklySchedule: "Weekly Schedule",
    noDoctors: "No doctors found",
    searchBySpecialization: "Search by name or specialization...",
    bookWithDoctor: "Book with this doctor",
    yearsExp: "yrs experience",
    perConsultation: "consultation",

    // ─── Medical Records ───────────────────────────────────────────────────────
    noMedicalRecords: "No medical records found",
    medicalRecordsSubtitle: "Patient health history and diagnoses",
    diagnosis: "Diagnosis",
    followUp: "Follow-up",
    recordDetails: "Record Details",
    prescription: "Prescription",
    treatment: "Treatment",
    searchByDiagnosis: "Search by diagnosis or patient...",

    // ─── Billing ───────────────────────────────────────────────────────────────
    billingSubtitle: "Invoice management and payments",
    myBillsSubtitle: "Your invoices and payment history",
    invoiceDetails: "Invoice Details",
    invoiceNumber: "Invoice Number",
    balanceDue: "Balance Due",
    amountPaid: "Amount Paid",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    total: "Total",
    dueDate: "Due Date",
    paymentMethod: "Payment Method",
    processPayment: "Process Payment",
    processing: "Processing...",
    uploadReceipt: "Upload Receipt",
    submitReceipt: "Submit Receipt",
    payViaCard: "Pay via Card",
    paymentScreenshot: "Payment Screenshot",
    cardNumber: "Card Number",
    amountPaidLabel: "Amount Paid",
    cardLastFour: "Card Number (last 4 digits, optional)",
    noteLabel: "Note (optional)",
    clickToSelect: "Click to select file",
    cash: "Cash",
    card: "Card",
    insuranceMethod: "Insurance",
    bankTransfer: "Bank Transfer",
    online: "Online",
    paymentReceipts: "Payment Receipts",
    pendingReceiptsAlert: "pending payment receipt(s) awaiting confirmation",
    noBillsFound: "No bills found",
    searchInvoice: "Search by invoice or patient...",
    invoiceCol: "Invoice",
    patientCol: "Patient",
    amountCol: "Amount",
    paidCol: "Paid",
    balanceCol: "Balance",
    statusCol: "Status",
    receiptCol: "Receipt",
    dateCol: "Date",
    actionsCol: "Actions",
    paymentAmount: "Payment Amount",
    transferInstruction: "Transfer the amount to our card, then upload a screenshot of the payment confirmation below.",
    description: "Description",

    // ─── Departments ───────────────────────────────────────────────────────────
    departmentInfo: "Department Information",
    addDepartment: "Add Department",
    editDepartment: "Edit Department",
    deleteDepartment: "Delete Department",
    noDepartments: "No departments found",
    location: "Location",
    contactNumber: "Contact Number",
    departmentName: "Department name",
    departmentsCount: "departments",
    doctorsInDept: "Doctors",
    noDocsInDept: "No doctors in this department",
    deleteConfirmDept: "delete? This cannot be undone.",

    // ─── Blog ──────────────────────────────────────────────────────────────────
    blogSubtitle: "Medical insights and health tips",
    newPost: "New Post",
    editPost: "Edit Post",
    deletePost: "Delete Post",
    like: "Like",
    dislike: "Dislike",
    comment: "Comment",
    comments: "comments",
    reply: "Reply",
    noPostsYet: "No posts yet",
    firstToShare: "Be the first to share a medical insight.",
    noPostsAvailable: "No blog posts available yet.",
    postTitle: "Post title...",
    postContent: "Write your post content...",
    postImage: "Image (optional)",
    publish: "Publish",
    writeComment: "Write a comment...",
    writeReply: "Write a reply...",
    blogTitleLabel: "Title",
    blogContentLabel: "Content",
    blogImageLabel: "Image (optional)",

    // ─── Users ─────────────────────────────────────────────────────────────────
    userManagement: "User Management",
    allStaff: "Manage all staff and their roles",
    newEmployee: "New Employee",
    createUser: "Create User",
    editUser: "Edit User",
    deleteUser: "Delete",
    promoteToAdmin: "Make Admin",
    activateUser: "Activate / Deactivate",
    verifyUser: "Verification status",
    autoGenPassword: "Auto-generate password",
    loginPassword: "Login Password",
    givePasswordToDoctor: "Give this password to the doctor — they'll use it to log in.",
    accountCreated: "Account Created!",
    passwordForDoctor: "Give the following password to the doctor",
    copyPassword: "Copy",
    understood: "Got it",
    savePassword: "Save this password somewhere safe!",
    confirmDeleteUser: "delete?",
    confirmPromoteAdmin: "make admin?",
    profileImage: "Profile photo",
    imageOptional: "Photo upload is optional",
    minPassword: "Minimum 8 characters",
    repeatPassword: "Repeat",
    autoFromEmail: "Auto from email",
    doctorInfo2: "Doctor Information",
    specialization2: "Specialization",
    departmentSelect: "Department",
    experienceYears: "Experience (years)",
    consultationFee: "Consultation ($)",
    licenseField: "License",
    bioField: "Info / Bio",
    allRoles: "All Roles",

    // ─── Profile ───────────────────────────────────────────────────────────────
    myProfile: "My Profile",
    personalInfo: "Personal Information",
    changePassword: "Change Password",
    doctorProfile: "Doctor Profile",
    patientProfile: "Patient Profile",
    oldPassword: "Old password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    uploadAvatar: "Upload Photo",
    avatarHint: "Add a photo to your profile",
    saveChanges: "Save Changes",
    passwordChanged: "Password changed successfully",
    profileUpdated: "Profile updated",
  }
}

const useLanguageStore = create(
  persist(
    (set, get) => ({
      lang: 'uz',
      translations,
      setLang: (lang) => set({ lang }),
      t: (key) => {
        const currentLang = get().lang
        return translations[currentLang]?.[key] || translations['en']?.[key] || key
      },
    }),
    { name: 'language-storage' }
  )
)

export default useLanguageStore
